site_name: AI Programming in Python
# site_url: http://127.0.0.1:8000/
copyright: Atheris hispida
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
  - navigation.tracking
  - navigation.footer
  - navigation.expand
  - header.autohide
  - search.highlight
  - search.suggest
  - content.code.copy
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- admonition
- pymdownx.details
plugins:
- i18n:
    docs_structure: suffix
    languages:
    - locale: en
      default: true
      name: English
      build: true
    - locale: zh
      name: 中文
      build: true
      site_name: 人工智能程序设计
- search: null

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/chat.js
  - https://cdn.jsdelivr.net/npm/marked/marked.min.js
  - https://cdn.jsdelivr.net/npm/dompurify/dist/purify.min.js